### ISSUE TITLE
httpie is broken in latest netshoot

### ISSUE THREAD

**Issue by easimon** [nicolaka/netshoot#134]
This is not #69, but similar. With current netshoot:latest, httpie does not work anymore:

```
mesh-debug-pod# http                                                                          
Traceback (most recent call last):
  File "/usr/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie==3.2.1', 'console_scripts', 'http')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpie/__main__.py", line 8, in main
    from httpie.core import main
  File "/usr/lib/python3.11/site-packages/httpie/core.py", line 8, in <module>
    import requests
  File "/usr/lib/python3.11/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/usr/lib/python3.11/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/usr/lib/python3.11/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
mesh-debug-pod# 
```

**Comment by nicolaka** [comment]
fixed in latest/v0.10 !
