### ISSUE TITLE
httpie is broken

### ISSUE THREAD

**Issue by mamachanko** [nicolaka/netshoot#69]
```
$ docker run --rm -it nicolaka/netshoot http example.com

Traceback (most recent call last):
  File "/usr/bin/http", line 33, in <module>
    sys.exit(load_entry_point('httpie==2.4.0', 'console_scripts', 'http')())
  File "/usr/lib/python3.8/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/usr/lib/python3.8/site-packages/httpie/core.py", line 13, in <module>
    from httpie.client import collect_messages
  File "/usr/lib/python3.8/site-packages/httpie/client.py", line 15, in <module>
    from httpie.plugins.registry import plugin_manager
  File "/usr/lib/python3.8/site-packages/httpie/plugins/registry.py", line 1, in <module>
    from httpie.plugins.manager import PluginManager
  File "/usr/lib/python3.8/site-packages/httpie/plugins/manager.py", line 5, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'

```

**Comment by FlorianLoch** [comment]
Can confirm, same issue with me :(

**Comment by nicolaka** [comment]
I'm taking a look.

**Comment by nicolaka** [comment]
should be fixed now.

**Comment by mamachanko** [comment]
Thanks @nicolaka
